// <auto-generated />
using System;
using Filminurk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filminurk.Data.Migrations
{
    [DbContext(typeof(FilminurkTARpe24Context))]
    [Migration("20251121095529_service")]
    partial class service
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Filminurk.Core.Domain.Actors", b =>
                {
                    b.Property<Guid>("ActorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActorRegion")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FavoriteListID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoviesActedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PortraitID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorID");

                    b.HasIndex("FavoriteListID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FavoriteList", b =>
                {
                    b.Property<Guid>("FavoriteListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMovieOrActor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReported")
                        .HasColumnType("bit");

                    b.Property<string>("ListBelongsToUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ListCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ListDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ListModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavoriteListID");

                    b.ToTable("FavoriteLists");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FileToApi", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExistingFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPoster")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MovieID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageID");

                    b.ToTable("FilesToApi");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FileToDatabase", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ListID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageID");

                    b.ToTable("FileToDatabase");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CurrentRating")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EntryCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FavoriteListID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FirstPublished")
                        .HasColumnType("date");

                    b.Property<int?>("MovieGenre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FavoriteListID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.UserComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CommentDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CommentModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommentedScore")
                        .HasColumnType("int");

                    b.Property<string>("CommenterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHarmful")
                        .HasColumnType("int");

                    b.Property<int?>("IsHelpful")
                        .HasColumnType("int");

                    b.Property<Guid?>("MovieID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId");

                    b.HasIndex("MovieID");

                    b.ToTable("UserComments");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Actors", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.FavoriteList", null)
                        .WithMany("ListOfActors")
                        .HasForeignKey("FavoriteListID");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.FavoriteList", null)
                        .WithMany("ListOfMovies")
                        .HasForeignKey("FavoriteListID");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.UserComment", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.Movie", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MovieID");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FavoriteList", b =>
                {
                    b.Navigation("ListOfActors");

                    b.Navigation("ListOfMovies");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
